from snakemake.utils import min_version

# ------------- min snakemake version ------------
min_version("6.7.0")


# ------------- setup ------------
configfile: "config/config.yaml"

transfer_cli = str(config.get("transfer_cli", "false")).lower() == "true"

report: "report/workflow.rst"


# ------------- load rules ------------


include: "rules/common.smk"
include: "rules/archive.smk"
if transfer_cli:
   include: "rules/transfer_cli.smk"
else:
   include: "rules/transfer_flow.smk"


# ------------- workflow ------------


rule all:
    input:
        get_outputs(file_types),
        get_final_checksum_outputs(),
        get_archive_complete_outputs(),
        get_transfer_outputs(),
