site_name: Nanopore Transfer Automation
nav:
  - Setup: setup.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md
  - GitHub: https://github.com/WEHIGenomicsRnD/nanopore-transfer-automation
