# directory containing runs
data_dir: 'test'

# what to call directory for transfer
transfer_dir: '_transfer'

# minimum number of seconds a run needs
# to be finished before archiving
time_delay: 10

# directories exempt from the standard
# mask; use YAML lists for this arg
extra_dirs:
    - 'TEST_b'

# whether or not to calculate file checksums
calculate_checksums: True