# directory containing runs
data_dir: 'test'

# what to call directory for transfer
transfer_dir: '_transfer'

# file types to process in a list
# each item must match one of
# 'fastq', 'fast5' or 'reports'
file_types:
    - 'reports'
    - 'fastq'
    - 'fast5'

# project directory regex (do not change
# unless you know what you are doing)
proj_dir_regex: '^(\d{6,8})_([a-zA-Z0-9\-]+)_([a-zA-Z0-9\-]+)_([a-zA-Z0-9\-_]+)$'

# minimum number of seconds a run needs
# to be finished before archiving
time_delay: 10

# directories exempt from the standard
# mask; use YAML lists for this arg
extra_dirs:
    - 'TEST_b'

# whether or not to calculate file checksums
calculate_checksums: True

# NOTE that threads > 1 requires
# pigz to be installed
threads: 1