# directory containing runs (MUST be an absolute path)
data_dir: '/data'

# what to call directory for transfer
transfer_dir: '_transfer'

# file types to process in a list
# each item must match one of
# 'fastq', 'fast5', 'pod5',
# 'reports' and 'checksums'
# NOTE: you must specify only ONE
# of fast5 or pod5 per run
file_types:
    - 'reports'
    - 'fastq'
    - 'pod5'
    - 'checksums'

# project directory regex (set this based on
# your lab's naming convention)
proj_dir_regex: '^(\d{6,8})_([a-zA-Z0-9\-]+)_([a-zA-Z0-9\-]+)_([a-zA-Z0-9\-_]+)$'

# regex of run file that signifies that
# the run has finished (do not change
# unless you know what you are doing)
end_of_run_file_regex: '^sequencing_summary\w*\.txt'

# check if run is complete before processing
check_if_complete: True

# minimum number of seconds a run needs
# to be finished before archiving
time_delay: 0

# directories exempt from the standard
# mask; use YAML lists for this arg
extra_dirs:
    -

# do not process these directories
ignore_dirs:
    -

# set true if you only want to run the
# script on *only* the extra_dirs set above
ignore_proj_regex: False

# number of threads to use
threads: 12

# whether to transfer data upon archiving completion using Globus
transfer: False

# this machine's Globus endpoint ID
src_endpoint: ''

# Globus endpoint ID to transfer data to
dest_endpoint: ''

# Globus path to transfer data to
dest_path: ''